<template>
  <div class="absolute w-full h-full">
    <div class="modal-overlay absolute z-10">
      <div class="mx-auto mt-2 overflow-y-auto h-[98vh]">
        <!-- <p class="text-white">{{ analysis }}</p> -->
        <div class="grid grid-rows-2 gap-1 mx-auto flex-shrink-0">
          <div class="mx-auto" style="visibility:visible;">
            <div
              class="w-[210mm] absolute top-0 bg-black bg-opacity-0 hover:bg-opacity-75 hover:text-white p-2 mt-2 transition">
              <div class="flex flex-row justify-end gap-6 ">
                <button type="button my-auto" class="py-1" @click="generatePDF">
                  <span class="flex items-center">
                    <Icon name="mdi:download-outline" size="24" />
                    Download
                  </span>
                </button>
                <button type="button" class="py-1 my-auto" @click="$emit('close-preview')">
                  <span class="flex items-center">
                    <Icon name="mdi:close-outline" size="24" />
                  </span>
                </button>
              </div>
            </div>
            <div class="pdf-content" id="pdfContent1">
              <div class="content page-1">
                <div class="p-2 flex mb-4">
                  <img src="~/assets/DKI_LOGO_2.png" style="height: 6em;">
                  <div class="ml-8">
                    <p class="text-lg">LAPORAN HASIL PENGUKURAN</p>
                    <p class="text-lg">PRODUKTIVITAS MAKRO PROVINSI: [PROVINSI]</p>
                    <p class="text-lg">TAHUN {{ new Date().getFullYear() }} </p>
                    <p class="text-xs">GENERATED BY KALKUPRO VER 2.0 P3D JAKARTA {{ new Date().toLocaleDateString() }}
                    </p>

                  </div>
                </div>
                <div class="border border-black p-2 mb-4">
                  <p class="text-lg font-bold">PROFIL WILAYAH</p>
                  <ol class="list-decimal ml-8 text-sm">
                    <li>
                      <p>JUMLAH PENDUDUK PROVINSI :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>JUMLAH ANGKATAN KERJA PROVINSI :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>PRODUK DOMESTIK REGIONAL BRUTO (ADHK) PROVINSI :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>UPAH RATA-RATA TENAGA KERJA PROVINSI :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>JUMLAH DAERAH TINGKAT II :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>JUMLAH LAPANGAN USAHA PROVINSI :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>JUMLAH JAM KERJA :</p>
                      <p>...</p>
                    </li>
                  </ol>
                </div>
                <div class="border border-black p-2 mb-4">
                  <p class="text-lg font-bold">HASIL PENGUKURAN PRODUKTIVITAS MAKRO</p>
                  <ol class="list-decimal ml-8 text-sm">
                    <li>
                      <p>PRODUKTIVITAS TENAGA KERJA (juta/orang/tahun) :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>PERTUMBUHAN PRODUKTIVITAS TENAGA KERJA yoy (%) :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>PRODUKTIVITAS UPAH :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>PRODUKTIVITAS JAM KERJA (juta/orang/jam) :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>PERBANDINGAN PRODUKTIVITAS ANTARA KAB./KOTA :</p>
                      <p>...</p>
                    </li>
                  </ol>
                </div>

                <div class="border border-black p-2 mb-4">
                  <p class="text-lg font-bold">HASIL PENGUKURAN PRODUKTIVITAS MAKRO PER DAERAH TINGKAT II (DALAM
                    DIAGRAM)</p>

                </div>
                <!-- <div>
                  <img src="../assets/QR_Pak_Tsani.png" alt="" srcset="" style="height: 4em;" class="qr-ttd">
                </div> -->
              </div>

            </div>
            <div class="pdf-content " id="pdfContent2">
              <div class="content page-2">
                <div class="border border-black p-2 mb-4">
                  <p class="text-lg font-bold">HASIL PENGUKURAN PRODUKTIVITAS PER LAPANGAN USAHA (RINGKASAN):</p>
                  <ol class="list-decimal ml-8 text-sm">
                    <li>
                      <p>SEKTOR DENGAN KONTRIBUSI TERBESAR PADA PDRB :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>SEKTOR DENGAN KONTRIBUSI TERBESAR PADA PENYERAPAN TENAGA KERJA :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>SEKTOR DENGAN PRODUKTIVITAS TERTINGGI :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>SEKTOR DENGAN PRODUKTIVITAS TERENDAH :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>SEKTOR DENGAN PENINGKATAN PRODUKTIVITAS TERTINGGI :</p>
                      <p>...</p>
                    </li>
                    <li>
                      <p>SEKTOR DENGAN PENINGKATAN PRODUKTIVITAS TERENDAH :</p>
                      <p>...</p>
                    </li>
                  </ol>
                  <p class="text-lg font-bold mt-8">HASIL PENGUKURAN PRODUKTIVITAS SEKTORAL PER LAPANGAN USAHA (DALAM
                    DIAGRAM)</p>
                  <p class="text-lg font-bold mt-8">HASIL PENGUKURAN PRODUKTIVITAS SEKTORAL PER LAPANGAN USAHA PER
                    DAERAH TIGKAT II (DALAM DIAGRAM)</p>
                </div>
              </div>
            </div>
          </div>


        </div>
      </div>
    </div>
  </div>

</template>

<script setup>
import jsPDF from "jspdf";
import html2canvas from 'html2canvas';

const props = defineProps(["analysis"])

const modal = ref({
  show: false,
})

// let authUser
// if (process.client) {
//   authUser = ref(JSON.parse(localStorage.getItem("auth")))
// }

// let nomorSertifikat = computed(() => {
//   let nomor = props.analysis.id_laporan.replace(/\D/g, "")
//   return nomor.slice(0, 5)
// })

// let result = props.analysis.result

// let penilaian = computed(() => {
//   if (result.pr1 < (58 * (10 ** 6))) {
//     return "Sangat Rendah"
//   } else if (result.pr1 >= 58 * (10 ** 6) && result.pr1 < (80 * (10 ** 6))) {
//     return "Rendah"
//   } else if (result.pr1 >= 80 * (10 ** 6) && result.pr1 < (100 * (10 ** 6))) {
//     return "Sedang"
//   } else if (result.pr1 >= 100 * (10 ** 6)) {
//     return "Tinggi"
//   }
// })

// import { Bar, Line } from 'vue-chartjs';
// import {
//   Chart as ChartJS,
//   Title,
//   Tooltip,
//   Legend,
//   BarElement,
//   CategoryScale,
//   LinearScale,
// } from 'chart.js';

// import { ref } from 'vue';
// ChartJS.register(
//   Title,
//   Tooltip,
//   Legend,
//   BarElement,
//   CategoryScale,
//   LinearScale
// );

// const produktivitas_tenaga_kerja = ref({
//   labels: props.analysis.year,
//   datasets: [
//     {
//       label: 'Nilai Tambah / Jml Tenaga Kerja',
//       backgroundColor: '#e41a1c',
//       data: [result.kn1],
//     },
//     {
//       label: 'Nilai Tambah / Jam Kerja',
//       backgroundColor: '#377eb8',
//       data: [result.kn2],
//     },
//     {
//       label: 'Nilai Tambah / Biaya Tenaga Kerja',
//       backgroundColor: '#4daf4a',
//       data: [result.kn3],
//     },
//     {
//       label: 'Biaya Tenaga Kerja / Total Jam Kerja',
//       backgroundColor: '#ff7f00',
//       data: [result.kn4],
//     },
//   ],
// });

// const produktivitas = ref({
//   labels: props.analysis.year,
//   datasets: [
//     {
//       label: `Produktivitas ${props.analysis.year}`,
//       backgroundColor: '#377eb8',
//       data: [result.pr2 ? result.pr2 : 0, result.pr1],
//       barThickness: 48
//     },
//   ],
// })

// const nilaiTambah = ref({
//   labels: props.analysis.year,
//   datasets: [
//     {
//       label: `Nilai Tambah ${props.analysis.year}`,
//       backgroundColor: '#377eb8',
//       data: [result.nt2 ? result.nt2 : 0, result.nt],
//       barThickness: 48
//     },
//   ],
// })

// const chartOptions1 = {
//   responsive: true,
//   maintainAspectRatio: false,
//   devicePixelRatio: 4,
//   plugins: {
//     tooltip: {
//       enabled: false
//     },
//     title: {
//       text: "Nilai Tambah (Rupiah)",
//       display: true,
//       font: {
//         size: 14,
//         wight: 'bold'
//       }
//     },
//     legend: {
//       display: false,
//       position: "right",
//       maxWidth: 200,
//       labels: {
//         boxWidth: 12,
//         font: {
//           size: 10
//         }
//       }
//     }
//   },
//   scales: {
//     x: {
//       border: {
//         display: true
//       },
//       grid: {
//         display: true,
//         drawOnChartArea: false,
//         drawTicks: false,
//       }
//     },
//     y: {
//       border: {
//         display: true
//       },
//       grid: {
//         display: true,
//         drawOnChartArea: true,
//         drawTicks: false
//       }
//     }
//   }
// }

// const chartOptions2 = {
//   responsive: true,
//   maintainAspectRatio: false,
//   devicePixelRatio: 4,
//   plugins: {
//     tooltip: {
//       enabled: false
//     },
//     title: {
//       text: "Produktivitas (Rupiah)",
//       display: true,
//       font: {
//         size: 14,
//         wight: 'bold'
//       }
//     },
//     legend: {
//       display: false,
//       position: "right",
//       maxWidth: 200,
//       labels: {
//         boxWidth: 12,
//         font: {
//           size: 10
//         }
//       }
//     }
//   },
//   scales: {
//     x: {
//       border: {
//         display: true
//       },
//       grid: {
//         display: true,
//         drawOnChartArea: false,
//         drawTicks: false,
//       }
//     },
//     y: {
//       border: {
//         display: true
//       },
//       grid: {
//         display: true,
//         drawOnChartArea: true,
//         drawTicks: false
//       }
//     }
//   }
// }

// const chartOptions3 = {
//   responsive: true,
//   maintainAspectRatio: false,
//   devicePixelRatio: 4,
//   plugins: {
//     tooltip: {
//       enabled: false
//     },
//     title: {
//       text: "Kenaikan Pertumbuhan Produktivitas Tenaga Kerja (%)",
//       display: true,
//       font: {
//         size: 14,
//         wight: 'bold'
//       }
//     },
//     legend: {
//       display: true,
//       position: "right",
//       maxWidth: 200,
//       labels: {
//         boxWidth: 12,
//         font: {
//           size: 10
//         }
//       }
//     }
//   },
//   scales: {
//     x: {
//       border: {
//         display: true
//       },
//       grid: {
//         display: true,
//         drawOnChartArea: false,
//         drawTicks: false,
//       }
//     },
//     y: {
//       border: {
//         display: true
//       },
//       grid: {
//         display: true,
//         drawOnChartArea: true,
//         drawTicks: false
//       }
//     }
//   }
// }

const generatePDF = async () => {
  let title = `[example] Sertifikat_Produktivitas.pdf`

  const htmlContent1 = document.getElementById('pdfContent1');
  const canvas = await html2canvas(htmlContent1, {
    scale: 2,
    useCORS: true,
    logging: true,
    letterRendering: 1,
    allowTaint: true,
    foreignObjectRendering: true
  });

  const doc = new jsPDF({
    orientation: "p",
    unit: 'mm',
    format: "a4",
    compress: true
  });

  const imgWidth = 210; // A4 width in mm
  const pageHeight = 297; // A4 height in mm
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  // Split content across multiple pages if needed
  let heightLeft = imgHeight;
  let position = 0;

  // First page
  doc.addImage(canvas, 'PNG', 0, 0, imgWidth, imgHeight, undefined, 'FAST');
  heightLeft -= pageHeight;

  // Additional pages if content overflows
  while (heightLeft >= 0) {
    position = heightLeft - imgHeight;
    doc.addPage();
    doc.addImage(canvas, 'PNG', 0, position, imgWidth, imgHeight, undefined, 'FAST');
    heightLeft -= pageHeight;
  }

  doc.save(title);
}


</script>

<style scoped>
.modal-overlay {
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  justify-content: center;
  background-color: #000000da;
}

.close {
  cursor: pointer;
}

.pdf-content {
  background-color: #ffffff;
  background-repeat: no-repeat;
  background-size: contain;
  /* background-position: center center; */
  /* Set your desired background color */
  height: 297mm;
  width: 210mm;
}

.pdf-content-2 {
  background-color: #ffffff;
  /* background-color: #fffff6; */
  /* background-color: #b1b116; */
  background-repeat: no-repeat;
  background-size: contain;
  /* background-position: center center; */
  /* Set your desired background color */
  height: 297mm;
  width: 210mm;
}

.qr-ttd {
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 1em;
  margin-top: 1.5em;
}

.content {
  padding: 4em 7em 3em;
}

.title {
  font-family: 'Times New Roman', Times, serif;
  text-align: center;
}

.title-text {
  font-size: 1em;
}

.normal-text {
  font-family: 'Times New Roman', Times, serif;
  font-size: 1em;
  text-align: center;
}

.nomor-sertif {
  font-family: Arial, Helvetica, sans-serif;
  font-weight: 800;
  font-size: 1.25em;
  text-align: center;
  margin-top: 1.6em;
}

.perusahaan {
  font-family: Arial, Helvetica, sans-serif;
  font-weight: 800;
  font-size: 2em;
  text-align: center;
  margin-top: 1.5em;
  line-height: 1.2;
  height: 2.5em;
}

.table,
td {
  border: 1px solid;
  padding-bottom: 10px;
}

.content-2 {
  padding: 2em 3em 2em;
}

.header-2 {
  margin-left: auto;
  margin-right: auto;
  color: white;
  background-color: #c35752;
  border-radius: 10em;
  padding: 0em 1em 1em 1em;
  font-family: 'Times New Roman', Times, serif;
  font-size: 1.4em;
  font-weight: 600;
  text-align: center;
}
</style>