<template>
  <div class="absolute w-full h-full">
    <div class="modal-overlay absolute z-10">
      <div class="mx-auto mt-2 overflow-y-auto h-[98vh]">
        <!-- <p class="text-white">{{ analysis }}</p> -->
        <div class="grid grid-rows-2 gap-1 mx-auto flex-shrink-0">
          <div class="mx-auto" style="visibility:visible;">
            <div
              class="w-[210mm] absolute top-0 bg-black bg-opacity-25 hover:bg-opacity-75 hover:text-white p-2 mt-2 transition z-50">
              <div class="flex flex-row justify-end gap-6 ">
                <button type="button my-auto" class="py-1" @click="generatePDF">
                  <span class="flex items-center">
                    <Icon name="mdi:download-outline" size="24" />
                    Download
                  </span>
                </button>
                <button type="button" class="py-1 my-auto" @click="$emit('close-preview')">
                  <span class="flex items-center">
                    <Icon name="mdi:close-outline" size="24" />
                  </span>
                </button>
              </div>
            </div>
            <div class="pdf-content" id="pdfContent-1">
              <div class="content page-1">
                <p class="page-number text-center">1</p>
                <div class="p-2 flex mb-4">
                  <img src="~/assets/logo_copy.png" style="height: 6em;">
                  <div class="ml-8">
                    <p class="">Laporan Hasil Pengukuran</p>
                    <p class="">Produktivitas Makro Provinsi: {{ rawData.metadata.provinsi.replace('Provinsi ', '') }}
                    </p>
                    <p class="">Tahun {{ rawData.metadata.tahun[rawData.metadata.tahun.length - 1] }} </p>
                    <p class="text-xs">GENERATED BY KALKUPRO VER 2.0 P3D JAKARTA {{ new Date().toLocaleDateString() }}
                    </p>

                  </div>
                </div>
                <div class="border border-black p-2 mb-4">
                  <p class="text-lg font-bold">Profil Wilayah</p>
                  <table class="w-full text-sm table-auto no-border">
                    <tbody>
                    <tr class="">
                      <td class="">1. Jumlah Penduduk Provinsi</td>
                      <td class="px-2 ">:</td>
                      <td class="">{{ rawData.metadata.jumlah_penduduk }} Orang</td>
                    </tr>
                    <tr class="">
                      <td class="">2. Jumlah Angkatan Kerja Provinsi</td>
                      <td class="px-2 ">:</td>
                      <td class="">{{ rawData.metadata.jumlah_angkatan_kerja }} Orang</td>
                    </tr>
                    <tr class="">
                      <td class="">3. Produk Domestik Regional Bruto (ADHK) Provinsi</td>
                      <td class="px-2 ">:</td>
                      <td class="">Rp {{ rawData.metadata.produk_domestik_regional_bruto.toLocaleString('id-ID') }}</td>
                    </tr>
                    <tr class="">
                      <td class="">4. Upah Rata-Rata Tenaga Kerja Provinsi</td>
                      <td class="px-2 ">:</td>
                      <td class="">Rp {{ rawData.metadata.upah_rata_rata_tenaga_kerja.toLocaleString('id-ID') }}</td>
                    </tr>
                    <tr class="">
                      <td class="">5. Jumlah Daerah Tingkat II</td>
                      <td class="px-2 ">:</td>
                      <td class="">{{ rawData.metadata.jumlah_daerah_tingkat_ii }}</td>
                    </tr>
                    <tr class="">
                      <td class="">6. Jumlah Lapangan Usaha Provinsi</td>
                      <td class="px-2 ">:</td>
                      <td class="">{{ rawData.metadata.jumlah_lapangan_usaha }}</td>
                    </tr>
                    <tr class="">
                      <td class="">7. Jumlah Jam Kerja</td>
                      <td class="px-2 ">:</td>
                      <td class="">{{ rawData.metadata.jumlah_jam_kerja }} jam</td>
                    </tr>
                    </tbody>
                  </table>
                </div>
                <div class="border border-black p-2 mb-4">
                  <p class="text-lg font-bold">Hasil Pengukuran Produktivitas Makro</p>
                  <ol class="list-none ml-2 text-sm">
                    <li>
                      <p>1. Produktivitas Tenaga Kerja (juta/orang/tahun) :</p>
                      <div class="w-[120mm]">
                        <GraphReportingLineChart :chart-data="data_1" title="" :key="state" :millions="true"
                          :options="{ legends: false, datalabels: true }" />
                      </div>
                    </li>
                    <li>
                      <p>2. Pertumbuhan Produktivitas Tenaga Kerja yoy (%) :</p>
                      <div class="w-[120mm]">
                        <GraphReportingLineChart :chart-data="data_2" title="" :key="state" :millions="false"
                          :options="{ legends: false, datalabels: true }" />
                      </div>
                    </li>
                  </ol>
                </div>

              </div>

            </div>
            <div class="pdf-content" id="pdfContent-2">
              <div class="content page-2">
                <p class="page-number text-center">2</p>
                <div class="border border-black p-2 mb-4">
                  <ol class="list-none ml-2 text-sm" start="3">
                    <li>
                      <p>3. Produktivitas Upah :</p>
                      <div class="w-[120mm]">
                        <GraphReportingLineChart :chart-data="data_3" title="" :key="state"
                          :options="{ legends: false, datalabels: true }" />
                      </div>
                    </li>
                    <li>
                      <p>4. Produktivitas Jam Kerja (juta/orang/jam) :</p>
                      <div class="w-[120mm]">
                        <GraphReportingLineChart :chart-data="data_4" title="" :millions="true" :key="state"
                          :options="{ legends: false, datalabels: true }" />
                      </div>
                    </li>
                    <li>
                      <p>5. Perbandingan Produktivitas Antara Kab./Kota :</p>
                      <div class="w-[140mm]">
                        <GraphReportingLineChart :chart-data="data_5" title="" :millions="true" :key="state"
                          :options="{ legends: true, datalabels: false, yLabel: true, aspectRatio: 1.5 }" />
                      </div>
                    </li>
                  </ol>
                </div>
              </div>
            </div>
            <div class="pdf-content" id="pdfContent-3">
              <div class="content page-3">
                <p class="page-number text-center">3</p>
                <div class="border border-black p-2 mb-2">
                  <p class="text-lg font-bold">Hasil Pengukuran Produktivitas Per Lapangan Usaha (Ringkasan):</p>
                  <ol class="list-none ml-2 text-sm mt-4">
                    <li class="">

                      <table class="w-full">
                        <tbody>
                        <tr>
                          <td :colspan="3" class="pl-2 bg-slate-200">1. Sektor Dengan Kontribusi Terbesar Pada PDRB :
                          </td>
                        </tr>
                        <tr>
                          <td class="px-2">{{ data_6["Sektor PDRB terbesar"][0] }}</td>
                          <td class="px-2 w-[60%]">{{ data_6["Sektor PDRB terbesar"][1] }}</td>
                            <td class="px-2 w-[35%]">{{ data_6["Sektor PDRB terbesar"][2] }}</td>
                          </tr>
                        </tbody>
                      </table>
                    </li>
                    <li class="">

                      <table class="w-full">
                        <tbody>
                        <tr>
                          <td :colspan="3" class="pl-2 bg-slate-200">2. Sektor Dengan Kontribusi Terbesar Pada
                            Penyerapan Tenaga Kerja :</td>
                        </tr>
                        <tr>
                          <td class="px-2">{{ data_6["Sektor Penyerapan TK terbesar"][0] }}</td>
                          <td class="px-2 w-[60%]">{{ data_6["Sektor Penyerapan TK terbesar"][1] }}</td>
                          <td class="px-2 w-[35%]">{{ data_6["Sektor Penyerapan TK terbesar"][2] }}</td>
                        </tr>
                        </tbody>
                      </table>
                    </li>
                    <li class="">

                      <table class="w-full">
                        <tbody>
                        <tr>
                          <td :colspan="3" class="pl-2 bg-slate-200">3. Sektor Dengan Produktivitas Tertinggi (orang/tahun):</td>
                        </tr>
                        <tr>
                          <td class="px-2">{{ data_6["Sektor Produktivitas terbesar"][0] }}</td>
                          <td class="px-2 w-[60%]">{{ data_6["Sektor Produktivitas terbesar"][1] }}</td>
                          <td class="px-2 w-[35%]">Rp {{ data_6["Sektor Produktivitas terbesar"][2] }}</td>
                        </tr>
                        </tbody>
                      </table>
                    </li>
                    <li class="">

                      <table class="w-full">
                        <tbody>
                        <tr>
                          <td :colspan="3" class="pl-2 bg-slate-200">4. Sektor Dengan Produktivitas Terendah (orang/tahun):</td>
                        </tr>
                        <tr>
                          <td class="px-2">{{ data_6["Sektor Produktivitas terendah"][0] }}</td>
                          <td class="px-2 w-[60%]">{{ data_6["Sektor Produktivitas terendah"][1] }}</td>
                            <td class="px-2 w-[35%]">Rp {{ data_6["Sektor Produktivitas terendah"][2] }}</td>
                          </tr>
                        </tbody>
                      </table>
                    </li>
                    <li class="">

                      <table class="w-full">
                        <tbody>
                        <tr>
                          <td :colspan="3" class="pl-2 bg-slate-200">5. Sektor Dengan Peningkatan Produktivitas
                            Tertinggi (%):</td>
                        </tr>
                        <tr>
                          <td class="px-2">{{ data_6["Sektor Peningkatan Produktivitas terbesar"][0] }}</td>
                          <td class="px-2 w-[60%]">{{ data_6["Sektor Peningkatan Produktivitas terbesar"][1] }}</td>
                              <td class="px-2 w-[35%]">{{ data_6["Sektor Peningkatan Produktivitas terbesar"][2] }}</td>
                            </tr>
                          </tbody>
                        </table>
                      </li>
                      <li class="">

                      <table class="w-full items-center">
                        <tbody>
                          <tr>
                            <td :colspan="3" class="pl-2 bg-slate-200">6. Sektor Dengan Peningkatan Produktivitas
                              Terendah (%)
                              :</td>
                          </tr>
                          <tr>
                            <td class="px-2 align-middle">{{ data_6["Sektor Peningkatan Produktivitas terendah"][0] }}
                            </td>
                            <td class="px-2 w-[60%] align-middle">
                              {{ data_6["Sektor Peningkatan Produktivitas terendah"][1] }}</td>
                            <td class="px-2 w-[35%] align-middle">
                              {{ data_6["Sektor Peningkatan Produktivitas terendah"][2] }}</td>
                          </tr>
                        </tbody>
                      </table>
                    </li>
                  </ol>

                  <p class="text-lg font-bold mt-2">Hasil Pengukuran Produktivitas Sektoral Per Lapangan Usaha (Dalam
                    Diagram)</p>
                  <p class="text-center text-sm">Tabel 1. Pengukuran Produktivitas Makro DKI Jakarta</p>
                  <table class="w-full text-xs font-normal mt-4">
                    <tbody>
                      <tr class="">
                        <td class="w-[5%] text-center">No</td>
                        <td class="w-[5%] text-center">Kode</td>
                        <td class="w-[45%]">Deskripsi</td>
                        <td class="w-[7%] text-center">Tahun</td>
                        <td class="w-[30%]">Produktivitas (rp/orang/tahun)</td>
                      </tr>
                      <template v-for="(_, groupIndex) in 2">
                        <tr v-for="(_, yearIndex) in 5" :key="`group${groupIndex}-year${yearIndex}`">
                          <td class="text-center">{{ groupIndex * 5 + yearIndex + 1 }}</td>
                          <template v-if="yearIndex === 0">
                            <td class="text-center" :rowspan="5">{{ data_7['kode'][groupIndex * 5] }}
                            </td>
                            <td :rowspan="5">{{ data_7['deskripsi'][groupIndex * 5] }}</td>
                          </template>
                          <td class="text-center">{{ data_7['tahun'][groupIndex * 5 + yearIndex] }}</td>
                          <td class="text-end px-2">{{ data_7['produktivitas'][groupIndex * 5 + yearIndex
                          ] }}</td>
                        </tr>
                      </template>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            <div class="pdf-content" id="pdfContent-4">
              <div class="content page-4">
                <p class="page-number text-center">4</p>
                <div class="border border-black p-2 mb-4">
                  <table class="w-full text-xs font-normal">
                    <tbody> 
                      <tr class="">
                        <td class="w-[5%] text-center">No</td>
                        <td class="w-[5%] text-center">Kode</td>
                        <td class="w-[45%]">Deskripsi</td>
                        <td class="w-[7%] text-center">Tahun</td>
                        <td class="w-[30%]">Produktivitas (rp/orang/tahun)</td>
                      </tr>
                      <template v-for="(_, groupIndex) in 6">
                        <tr v-for="(_, yearIndex) in 5" :key="`group${groupIndex}-year${yearIndex}`">
                          <td class="text-center">{{ groupIndex * 5 + yearIndex + 11 }}</td>
                          <template v-if="yearIndex === 0">
                            <td class="text-center" :rowspan="5">{{ data_7['kode'][groupIndex * 5 + 10] }}
                            </td>
                            <td :rowspan="5">{{ data_7['deskripsi'][groupIndex * 5 + 10] }}</td>
                          </template>
                          <td class="text-center">{{ data_7['tahun'][groupIndex * 5 + yearIndex + 10] }}</td>
                          <td class="text-end px-2">{{ data_7['produktivitas'][groupIndex * 5 + yearIndex
                            + 10] }}</td>
                        </tr>
                      </template>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            <div class="pdf-content" id="pdfContent-5">
              <div class="content page-5">
                <p class="page-number text-center">5</p>
                <div class="border border-black p-2 mb-4">
                  <table class="w-full text-xs font-normal">
                    <tbody>
                      <tr class="">
                        <td class="w-[5%] text-center">No</td>
                        <td class="w-[5%] text-center">Kode</td>
                        <td class="w-[45%]">Deskripsi</td>
                        <td class="w-[7%] text-center">Tahun</td>
                        <td class="w-[30%]">Produktivitas (rp/orang/tahun)</td>
                      </tr>
                      <template v-for="(_, groupIndex) in 6">
                        <tr v-for="(_, yearIndex) in 5" :key="`group${groupIndex}-year${yearIndex}`">
                          <td class="text-center">{{ groupIndex * 5 + yearIndex + 41 }}</td>
                          <template v-if="yearIndex === 0">
                            <td class="text-center" :rowspan="5">{{ data_7['kode'][groupIndex * 5 + 40] }}
                            </td>
                            <td :rowspan="5">{{ data_7['deskripsi'][groupIndex * 5 + 40] }}</td>
                          </template>
                          <td class="text-center">{{ data_7['tahun'][groupIndex * 5 + yearIndex + 40] }}</td>
                          <td class="text-end px-2">{{ data_7['produktivitas'][groupIndex * 5 + yearIndex
                            + 40] }}</td>
                        </tr>
                      </template>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            <div class="pdf-content" id="pdfContent-6">
              <div class="content page-6">
                <p class="page-number text-center">6</p>
                <div class="border border-black p-2 mb-4">
                  <table class="w-full text-xs font-normal">
                    <tbody>
                      <tr class="">
                        <td class="w-[5%] text-center">No</td>
                        <td class="w-[5%] text-center">Kode</td>
                        <td class="w-[45%]">Deskripsi</td>
                        <td class="w-[7%] text-center">Tahun</td>
                        <td class="w-[30%]">Produktivitas (rp/orang/tahun)</td>
                      </tr>
                      <template v-for="(_, groupIndex) in 3">
                        <tr v-for="(_, yearIndex) in 5" :key="`group${groupIndex}-year${yearIndex}`">
                          <td class="text-center">{{ groupIndex * 5 + yearIndex + 71 }}</td>
                          <template v-if="yearIndex === 0">
                            <td class="text-center" :rowspan="5">{{ data_7['kode'][groupIndex * 5 + 70] }}
                            </td>
                            <td :rowspan="5">{{ data_7['deskripsi'][groupIndex * 5 + 70] }}</td>
                          </template>
                          <td class="text-center">{{ data_7['tahun'][groupIndex * 5 + yearIndex + 70] }}</td>
                          <td class="text-end px-2">{{ data_7['produktivitas'][groupIndex * 5 + yearIndex
                            + 70] }}</td>
                        </tr>
                      </template>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            <template
              v-for="(region, regionIndex) in Object.keys(rawData.data).filter(key => key !== 'Provinsi DKI Jakarta')">
              <div class="pdf-content" :id="`pdfContent-${7 + regionIndex * 3}`">
                <div class="content page-7">
                  <p class="page-number text-center">{{ regionIndex * 3 + 7 }}</p>
                  <div class="border border-black p-2 mb-4">
                    <p class="text-lg font-bold mb-1">Hasil Pengukuran Produktivitas Makro Per Daerah Tingkat II (Dalam
                      Diagram)</p>
                    <p class="text-center text-sm mb-3">Tabel {{ regionIndex + 2 }}. Pengukuran Produktivitas Makro {{
                      region
                      }}</p>
                    <table class="w-full text-xs font-normal">
                      <tbody>
                        <tr class=""> 
                          <td class="w-[5%] text-center">No</td>
                          <td class="w-[5%] text-center">Kode</td>
                          <td class="w-[45%]">Deskripsi</td>
                          <td class="w-[7%] text-center">Tahun</td>
                          <td class="w-[30%]">Produktivitas (rp/orang/tahun)</td>
                        </tr>
                        <template v-for="(_, groupIndex) in 6">
                          <tr v-for="(_, yearIndex) in 5" :key="`group${groupIndex}-year${yearIndex}`">
                            <td class="text-center">{{ groupIndex * 5 + yearIndex + 1 }}</td>
                            <template v-if="yearIndex === 0">
                              <td class="text-center" :rowspan="5">{{ data_8[region]['kode'][groupIndex * 5] }}</td>
                              <td :rowspan="5">{{ data_8[region]['deskripsi'][groupIndex * 5] }}</td>
                            </template>
                            <td class="text-center">{{ data_8[region]['tahun'][groupIndex * 5 + yearIndex] }}</td>
                            <td class="text-end px-2">{{ data_8[region]['produktivitas'][groupIndex * 5 + yearIndex] }}
                            </td>
                          </tr>
                        </template>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div class="pdf-content" :id="`pdfContent-${8 + regionIndex * 3}`">
                <div class="content page-8">
                  <p class="page-number text-center">{{ regionIndex * 3 + 8 }}</p>
                  <div class="border border-black p-2 mb-4">
                    <table class="w-full text-xs font-normal">
                      <tbody>
                        <tr class="">
                          <td class="w-[5%] text-center">No</td>
                          <td class="w-[5%] text-center">Kode</td>
                          <td class="w-[45%]">Deskripsi</td>
                          <td class="w-[7%] text-center">Tahun</td>
                          <td class="w-[30%]">Produktivitas (rp/orang/tahun)</td>
                        </tr>
                        <template v-for="(_, groupIndex) in 6">
                          <tr v-for="(_, yearIndex) in 5" :key="`group${groupIndex}-year${yearIndex}`">
                            <td class="text-center">{{ groupIndex * 5 + yearIndex + 31 }}</td>
                            <template v-if="yearIndex === 0">
                              <td class="text-center" :rowspan="5">{{ data_8[region]['kode'][groupIndex * 5 + 30] }}
                              </td>
                              <td :rowspan="5">{{ data_8[region]['deskripsi'][groupIndex * 5 + 30] }}</td>
                            </template>
                            <td class="text-center">{{ data_8[region]['tahun'][groupIndex * 5 + yearIndex + 30] }}</td>
                            <td class="text-end px-2">{{ data_8[region]['produktivitas'][groupIndex * 5 + yearIndex +
                              30] }}</td>
                          </tr>
                        </template>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div class="pdf-content" :id="`pdfContent-${9 + regionIndex * 3}`">
                <div class="content page-9">
                  <p class="page-number text-center">{{ regionIndex * 3 + 9 }}</p>
                  <div class="border border-black p-2 mb-4">
                    <table class="w-full text-xs font-normal">
                      <tbody>
                        <tr class="">
                          <td class="w-[5%] text-center">No</td>
                          <td class="w-[5%] text-center">Kode</td>
                          <td class="w-[45%]">Deskripsi</td>
                          <td class="w-[7%] text-center">Tahun</td>
                          <td class="w-[30%]">Produktivitas (rp/orang/tahun)</td>
                        </tr>
                        <template v-for="(_, groupIndex) in 5">
                          <tr v-for="(_, yearIndex) in 5" :key="`group${groupIndex}-year${yearIndex}`">
                            <td class="text-center">{{ groupIndex * 5 + yearIndex + 61 }}</td>
                            <template v-if="yearIndex === 0">
                              <td class="text-center" :rowspan="5">{{ data_8[region]['kode'][groupIndex * 5 + 60] }}
                              </td>
                              <td :rowspan="5">{{ data_8[region]['deskripsi'][groupIndex * 5 + 60] }}</td>
                            </template>
                            <td class="text-center">{{ data_8[region]['tahun'][groupIndex * 5 + yearIndex + 60] }}</td>
                            <td class="text-end px-2">{{ data_8[region]['produktivitas'][groupIndex * 5 + yearIndex +
                              60] }}</td>
                          </tr>
                        </template>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </template>
          </div>


        </div>
      </div>
    </div>
    <Loading v-if="loading" text="Generating Report..." />
  </div>

</template>

<script setup>
import jsPDF from "jspdf";
import html2canvas from 'html2canvas';
import rawData from '~/assets/macro_2_restructured.json'

const props = defineProps(["analysis"])

const modal = ref({
  show: false,
})

const state = ref(0)

const loading = ref(false)

const data_1 = computed(() => {
  let dataset = {
    labels: ["2018", "2019", "2020", "2021", "2022"],
    datasets: [
      {
        label: "Produktivitas",
        data: null,
        backgroundColor: "#3867D6",
        borderRadius: 5,
      },
    ],
  }
  let calcData = rawData.data["Provinsi DKI Jakarta"]["TOTAL"]["produktivitas"].map(x => x ? parseFloat(x.replaceAll('.', '')) : x)
  dataset.datasets[0].data = calcData
  return dataset
})

const data_2 = computed(() => {
  let dataset = {
    labels: ["2018", "2019", "2020", "2021", "2022"],
    datasets: [
      {
        label: "Produktivitas",
        data: null,
        backgroundColor: "#3867D6",
        borderRadius: 5,
      },
    ],
  }
  let calcData = rawData.data["Provinsi DKI Jakarta"]["TOTAL"]["growth_produktivitas"].map(x => x ? parseFloat(x.replace(',', '.').replace('%', '')) : x)
  dataset.datasets[0].data = calcData
  return dataset
})

const data_3 = computed(() => {
  let dataset = {
    labels: rawData.metadata.tahun,
    datasets: [
      {
        label: "Produktivitas",
        data: null,
        backgroundColor: "#3867D6",
        borderRadius: 5,
      },
    ],
  }
  let calcData = rawData.data["Provinsi DKI Jakarta"]["TOTAL"]["upah"].map(x => x ? parseFloat(x.replaceAll(',', '.')) : x)
  dataset.datasets[0].data = calcData
  return dataset
})

const data_4 = computed(() => {
  let dataset = {
    labels: ["2018", "2019", "2020", "2021", "2022"],
    datasets: [
      {
        label: "Produktivitas",
        data: null,
        backgroundColor: "#3867D6",
        borderRadius: 5,
      },
    ],
  }
  let calcData = rawData.data["Provinsi DKI Jakarta"]["TOTAL"]["jam_kerja"].map(x => x ? parseFloat(x.replaceAll('.', '')) : x)
  dataset.datasets[0].data = calcData
  return dataset
})

const data_5 = computed(() => {
  let colors = ['#4CAF50',
    '#2196F3',
    '#FFC107',
    '#009688',
    '#F44336',
    '#9C27B0',
  ]
  let dataset = {
    labels: ["2018", "2019", "2020", "2021", "2022"],
    datasets: [
    ],
  }
  let keys = Object.keys(rawData.data)
  for (let i = 0; i < keys.length - 1; i++) {
    dataset.datasets.push({
      label: keys[i],
      data: rawData.data[keys[i]]["TOTAL"]["produktivitas"].map(x => x ? parseFloat(x.replaceAll('.', '')) : x),
      backgroundColor: colors[i],
      borderRadius: 5,
      borderColor: colors[i],
    })
    dataset.datasets[i].borderRadius = 5
  }
  return dataset
})

const data_6 = computed(() => {
  const provinsiRaw = rawData.raw["Provinsi DKI Jakarta"]
  const provinsiAnalysis = rawData.data["Provinsi DKI Jakarta"]
  let pdrb = Object.entries(provinsiRaw).reduce((max, [key, value]) => {
    const lastPDRB = value["PDRB (ADHK) (juta Rp)"]?.[4] || 0;
    return lastPDRB > (max.value?.["PDRB (ADHK) (juta Rp)"]?.[4] || 0) ? { key, value } : max;
  }, {})
  let tkmax = Object.entries(provinsiRaw).reduce((max, [key, value]) => {
    const lastTK = value["Jumlah Tenaga Kerja (Bekerja) Agustus"]?.[4] || 0;
    return lastTK > (max.value?.["Jumlah Tenaga Kerja (Bekerja) Agustus"]?.[4] || 0) ? { key, value } : max;
  }, {})
  let produktivias_max = Object.entries(provinsiAnalysis).reduce((max, [key, value]) => {
    const lastTK = parseFloat(value["produktivitas"]?.[4].replaceAll('.', '')) || 0;
    return lastTK > (parseFloat(max.value?.["produktivitas"]?.[4].replaceAll('.', '')) || 0) ? { key, value } : max;
  }, {})

  let produktivias_min = Object.entries(provinsiAnalysis).reduce((min, [key, value]) => {
    const lastTK = parseFloat(value["produktivitas"]?.[4].replaceAll('.', '')) || 0;
    if (!min.value) return { key, value };
    return lastTK < (parseFloat(min.value?.["produktivitas"]?.[4].replaceAll('.', '')) || 0) ? { key, value } : min;
  }, { value: null })

  let growth_produktivitas_max = Object.entries(provinsiAnalysis).reduce((max, [key, value]) => {
    const lastTK = parseFloat(value["growth_produktivitas"]?.[4].replace(',', '.').replace('%', '')) || 0;
    return lastTK > (parseFloat(max.value?.["growth_produktivitas"]?.[4].replace(',', '.').replace('%', '')) || 0) ? { key, value } : max;
  }, {})
  let growth_produktivitas_min = Object.entries(provinsiAnalysis).reduce((min, [key, value]) => {
    const lastTK = parseFloat(value["growth_produktivitas"]?.[4].replace(',', '.').replace('%', '')) || 0;
    return lastTK < (parseFloat(min.value?.["growth_produktivitas"]?.[4].replace(',', '.').replace('%', '')) || 0) ? { key, value } : min;
  }, {})

  const compiled = {
    "Sektor PDRB terbesar": { 0: `${pdrb.key}`, 1: `${pdrb.value["nama"]} `, 2: `Rp ${pdrb.value["PDRB (ADHK) (juta Rp)"][4].toLocaleString('id-ID')}` },
    "Sektor Penyerapan TK terbesar": { 0: `${tkmax.key}`, 1: `${tkmax.value["nama"]} `, 2: `${tkmax.value["Jumlah Tenaga Kerja (Bekerja) Agustus"][4].toLocaleString('id-ID')}` },
    "Sektor Produktivitas terbesar": { 0: `${produktivias_max.key}`, 1: `${produktivias_max.value["nama"]} `, 2: `${produktivias_max.value["produktivitas"][4].toLocaleString('id-ID')}` },
    "Sektor Produktivitas terendah": { 0: `${produktivias_min.key}`, 1: `${produktivias_min.value["nama"]} `, 2: `${produktivias_min.value["produktivitas"][4].toLocaleString('id-ID')}` },
    "Sektor Peningkatan Produktivitas terbesar": { 0: `${growth_produktivitas_max.key}`, 1: `${growth_produktivitas_max.value["nama"]} `, 2: `${growth_produktivitas_max.value["growth_produktivitas"][4].toLocaleString('id-ID')}` },
    "Sektor Peningkatan Produktivitas terendah": { 0: `${growth_produktivitas_min.key}`, 1: `${growth_produktivitas_min.value["nama"]} `, 2: `${growth_produktivitas_min.value["growth_produktivitas"][4].toLocaleString('id-ID')}` },
  }
  return compiled
})

const data_7 = computed(() => {
  let dataNew = rawData.data["Provinsi DKI Jakarta"]
  let compiledData = {
    kode: [],
    deskripsi: [],
    tahun: [],
    produktivitas: []
  }

  const kode = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M,N", "O", "P", "Q", "R,S,T,U"]

  for (let x of kode) {
    for (let i = 0; i < rawData.metadata.tahun.length; i++) {
      compiledData.kode.push(x)
      compiledData.deskripsi.push(dataNew[x]['nama'])
      compiledData.tahun.push(rawData.metadata.tahun[i])
      compiledData.produktivitas.push((dataNew[x]['produktivitas'][i]))
    }
  }
  return compiledData
})

const data_8 = computed(() => {

  const allKode = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M,N", "O", "P", "Q", "R,S,T,U"]
  let compiledData = {}

  for (let loc of Object.keys(rawData.data)) {
    if (loc !== "Provinsi DKI Jakarta") {
      let dataPackage = {
        kode: [],
        deskripsi: [],
        tahun: [],
        produktivitas: []
      }
      for (let x of allKode) {
        for (let i = 0; i < rawData.metadata.tahun.length; i++) {
          dataPackage.kode.push(x)
          dataPackage.deskripsi.push(rawData.data[loc][x]['nama'])
          dataPackage.tahun.push(rawData.metadata.tahun[i])
          dataPackage.produktivitas.push((rawData.data[loc][x]['produktivitas'][i]))
        }
      }
      compiledData[loc] = dataPackage
    }
  }
  return compiledData
})

const generatePDF = async () => {
  try {
    loading.value = true
    let title = `[example] Sertifikat_Produktivitas.pdf`

    const doc = new jsPDF({
      orientation: "p",
      unit: 'mm',
      format: "a4",
      compress: true
    });


    for (let i = 1; i <= 24; i++) {
      let canvas = await html2canvas(document.getElementById(`pdfContent-${i}`), {
        scale: 2,
      });
      if (i > 1) doc.addPage();
      doc.addImage(canvas, 'PNG', 0, 0, 210, 297);
    }

    // const htmlContent2 = document.getElementById('pdfContent-2')
    // const canvas2 = await html2canvas(htmlContent2, {
    //   scale: 2,
    // })

    // const htmlContent3 = document.getElementById('pdfContent-3')
    // const canvas3 = await html2canvas(htmlContent3, {
    //   scale: 2,
    // });

    // const htmlContent4 = document.getElementById('pdfContent-4')
    // let canvas4 = await html2canvas(htmlContent4, {
    //   scale: 2,
    // });

    // const htmlContent5 = document.getElementById('pdfContent-5')
    // let canvas5 = await html2canvas(htmlContent5, {
    //   scale: 2,
    // });

    // const htmlContent6 = document.getElementById('pdfContent-6')
    // let canvas6 = await html2canvas(htmlContent6, {
    //   scale: 2
    // });




    loading.value = false
    doc.save(title);
  } catch (error) {
    loading.value = false
    console.error('Error generating PDF:', error)
    throw error
  }
}


</script>

<style scoped>
.modal-overlay {
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  justify-content: center;
  background-color: #000000da;
}

.close {
  cursor: pointer;
}

.pdf-content {
  background-color: #ffffff;
  background-repeat: no-repeat;
  background-size: contain;
  margin-bottom: 0.5em;
  /* background-position: center center; */
  /* Set your desired background color */
  height: 297mm;
  width: 210mm;
}

.pdf-content-2 {
  background-color: #ffffff;
  /* background-color: #fffff6; */
  /* background-color: #b1b116; */
  background-repeat: no-repeat;
  background-size: contain;
  /* background-position: center center; */
  /* Set your desired background color */
  height: 297mm;
  width: 210mm;
}

.qr-ttd {
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 1em;
  margin-top: 1.5em;
}

.content {
  padding: 4em 7em 3em;
  position: relative;
  height: 100%;
}

.title {
  font-family: 'Times New Roman', Times, serif;
  text-align: center;
}

.title-text {
  font-size: 1em;
}

.normal-text {
  font-family: 'Times New Roman', Times, serif;
  font-size: 1em;
  text-align: center;
}

.nomor-sertif {
  font-family: Arial, Helvetica, sans-serif;
  font-weight: 800;
  font-size: 1.25em;
  text-align: center;
  margin-top: 1.6em;
}

.perusahaan {
  font-family: Arial, Helvetica, sans-serif;
  font-weight: 800;
  font-size: 2em;
  text-align: center;
  margin-top: 1.5em;
  line-height: 1.2;
  height: 2.5em;
}

.table,
td {
  border: 1px solid;
  padding-bottom: 10px;
}

.content-2 {
  padding: 2em 3em 2em;
}

.header-2 {
  margin-left: auto;
  margin-right: auto;
  color: white;
  background-color: #c35752;
  border-radius: 10em;
  padding: 0em 1em 1em 1em;
  font-family: 'Times New Roman', Times, serif;
  font-size: 1.4em;
  font-weight: 600;
  text-align: center;
}

.no-border {
  border: none;
}

.no-border td {
  border: none;
}

.page-number {
  position: absolute;
  bottom: 40px;
  right: 50%;
  font-size: 1em;
}
</style>