export interface PostReport {
  nama: string,
  tahun: number,
  semester: number,
  triwulan: any,
  penjualan: number,
  modal_operasi: number,
  total_investasi: number,
  total_penjualan_dan_modal: number,
  jumlah_tenaga_kerja: number,
  jumlah_jam_kerja: number,
  jumlah_jam_lembur: number,
  upah_dan_gaji_biaya_tenaga_kerja: number,
  dana_pensiun: number,
  tunjangan_tenaga_kerja: number,
  total_biaya_tenaga_kerja: number,
  laba_bersih: number,
  laba_operasi: number,
  total_laba: number,
  pajak_penghasilan: number,
  pajak_kekayaan: number,
  pajak_upah: number,
  total_pajak: number,
  penyusutan_gedung: number,
  penyusutan_peralatan_dan_mesin: number,
  total_penyusutan: number,
  bunga_pinjaman_jangka_panjang: number,
  bunga_pinjaman_jangka_pendek: number,
  total_bunga_pinjaman: number,
  kas_dan_bank: number,
  persediaan: number,
  piutang_dagang: number,
  piutang_lain: number,
  tanah: number,
  gedung: number,
  mesin_dan_peralatan: number,
  aktiva_tetap_lainnya: number,
  total_aktiva_perusahaan: number,
  pertanyaan_1: string,
  pertanyaan_2: string,
  pertanyaan_3: string,
  pertanyaan_4: string,
  pertanyaan_5: string,
  barang_dan_jasa_yang_dibeli: number,
  barang_yang_digunakan: number,
  bahan_baku: number,
  bahan_pengemas: number,
  total_bahan_yang_digunakan: number,
  pekerjaan_subkontrak: number,
  sewa_overhead: number,
  air_dan_listrik_overhead: number,
  asuransi_perusahaan: number,
  biaya_transport: number,
  pemeliharaan_mesin: number,
  biaya_supplies_dan_gedung: number,
  biaya_lain: number,
  total_overhead_produksi: number,
  sewa_administrasi: number,
  air_dan_listrik_administrasi: number,
  telepon: number,
  pos_dan_telegram: number,
  percetakan_stationary_dan_office_supplies: number,
  biaya_kendaraan: number,
  advertising: number,
  hiburan_entertainment: number,
  majalah_dan_surat_kabar: number,
  jamuan_makan: number,
  perbaikan_umum: number,
  biaya_bank: number,
  biaya_akuntan_dan_audit: number,
  biaya_bantuan_hukum_dan_jasa_profesional: number,
  komisi: number,
  biaya_umum: number,
  total_biaya_administrasi: number
}

export interface PostKaryawan {
  nama: string,
  nomor: string,
  kontak: string,
  jabatan: string,
  jenis_peserta: string
}

export interface PostKpi {
  produktivitas: {
    unit_dihasilkan: number,
    waktu_dibutuhkan: number,
    bahan_digunakan: number,
    produk_reject: number,
    target_kpi: number,
    capaian_kpi: number
  },
  sikap: {
    adaptasi: number,
    inisiatif: number,
    disiplin: number,
    sikap_terhadap_supervisi: number,
    sikap: number,
    kerjasama: number,
    kualitas_hasil_kerja: number,
    kuantitas_hasil_kerja: number,
    ketergantungan_dan_kemandirian: number,
    pengetahuan_dan_keterampilan: number,
    pengurusan_rumah_tangga: number
  }
}

export interface PutProfile {
  pengguna: {
    nama: string
  },
  perusahaan: {
    nama: string,
    nama_pemilik: string,
    nama_pimpinan: string,
    telp_fax: string,
    alamat: string,
    provinsi: string,
    kota: string,
    kecamatan: string,
    alamat_pabrik: string,
    tanggal_pendirian: string,
    klasifikasi_usaha: any,
    kontak_person: string,
    email: string,
    website: string
  }
}